### ISSUE TITLE
Target already exists

### ISSUE THREAD

**Issue by debelop13** [rakuten-frontend/grunt-appdmg#16]
Hello,

First time that I build all is ok, but second time I have to delete my target folder to can compile, exists any type of flag like overwrite: true or something like that?

> Running "appdmg:target" (appdmg) task
> [ 1/20] Looking for target...                [FAIL]
> >> Error: Target already exists
> Warning: Task "appdmg:target" failed. Use --force to continue.
> 
> Aborted due to warnings.

Thanks.

**Comment by htanjo** [comment]
This error comes from the original [node-appdmg](https://github.com/LinusU/node-appdmg), not grunt-appdmg. grunt-appdmg is just a wrapper.
According to the [appdmg's source code](https://github.com/LinusU/node-appdmg/blob/0fdd2b0c0c13d8b14f8358c53b401f7e8afc2718/lib/appdmg.js#L79-L87), this behavior is its spec and appdmg doesn't have such an `overwrite` flag.

If you really need this option, could you report it on [node-appdmg](https://github.com/LinusU/node-appdmg) project?
If you just want to fix the task error, please install [grunt-contrib-clean](https://github.com/gruntjs/grunt-contrib-clean) and register `clean` task before running `appdmg`.

Thanks.

**Comment by debelop13** [comment]
Reported in: https://github.com/LinusU/node-appdmg/issues/130
Anyway, grunt-contrib-clean is good option!

Thanks for your attention!!

**Comment by htanjo** [comment]
No problem! Thanks for reporting. 😄
