### ISSUE TITLE
Any plan to support gulp?

### ISSUE THREAD

**Issue by cssxn** [rakuten-frontend/grunt-appdmg#17]
Any plan to support gulp?

**Comment by htanjo** [comment]
No, on this project.
There is already [gulp-appdmg](https://www.npmjs.com/package/gulp-appdmg) plugin on npm.

Also gulp supports Node.js modules and [appdmg has own API](https://github.com/LinusU/node-appdmg#api). You can directly run appdmg without plugin like this:

```js
const gulp = require('gulp');
const appdmg = require('appdmg');

gulp.task('default', done => {
  const ee = appdmg({
    target: 'test.dmg',
    basepath: __dirname,
    specification: { ... }
  });
  ee.on('finish', done);
  ee.on('error', done);
});
```
