### ISSUE TITLE
Add option to sign DMG

### ISSUE THREAD

**Issue by Speuta** [rakuten-frontend/grunt-appdmg#18]
Can you add an option to sign the .dmg file giving .provisionfile path argument ?

**Comment by htanjo** [comment]
This "grunt-appdmg" is just a wrapper of "[node-appdmg](https://github.com/LinusU/node-appdmg)". Could you request the new feature on the [node-appdmg project](https://github.com/LinusU/node-appdmg)?
Thanks.
