### ISSUE TITLE
preventing install on non-mac?

### ISSUE THREAD

**Issue by shaunlebron** [rakuten-frontend/grunt-appdmg#2]
We run a project that creates installations for Windows/Mac/Linux.  We use `grunt-appdmg` for the mac part, but of course we have logic in place to prevent using it when running on Windows/Linux machines.

We noticed that our `npm install` fails on Linux/Windows.  So we have to include `grunt-appdmg` as an optionalDependency in package.json so we can run `npm install --no-optional` to prevent its installation on linux/windows.

Is it possible to make this fail gracefully for cross-platform setups without the `optionalDependency` workaround?

**Comment by htanjo** [comment]
As far as I know, `optionalDependency` is the best solution.
But I don't think `--no-optional` flag is necessary in your project. The [npm doc](https://docs.npmjs.com/files/package.json#optionaldependencies) says "build failures do not cause installation to fail" when using `optionalDependency`.

Anyway, I will add [`os` field](https://docs.npmjs.com/files/package.json#os) to my package.json.
Then npm on Win/Linux will skip to install `grunt-appdmg` immediately—before the installation error, when you use `optionalDependency`.

Thanks for the feedback!

**Comment by htanjo** [comment]
I added `"os": ["darwin"]` to the package.json and wrote about `optionalDependency` in README.
This update is released as `grunt-appdmg v0.3.1`.

**Comment by htanjo** [comment]
I think this issue has been fixed.
If you still have problem, please reopen this.
