### ISSUE TITLE
cannot pass arguments to appdmg

### ISSUE THREAD

**Issue by conceptualspace** [rakuten-frontend/grunt-appdmg#7]
for some reason i cannot pass arguments to appdmg like i can for other grunt tasks. for example,

grunt.task.run('appdmg:volume1') fails with this error:

"Verifying property appdmg.volume1 exists in config...ERROR

> > Unable to process task.
> > Warning: Required config property "appdmg.mac-generic" missing. Use --force to continue."

i am trying to dynamically name the target using <%= grunt.task.current.args[0] => 

this approach is working for the grunt-copy plugin, but for appdmg ive had to use a task alias and then specify a config property inside the alias function..

any input is appreciated. otherwise fantastic plugin! thanks!
## essentials from the config here:

grunt.loadNpmTasks('grunt-appdmg');

grunt.registerTask('release', function() {
    grunt.task.run('copy:main:volume1');
    grunt.task.run('appdmg:volume1');
}

appdmg: {
   options: {...stuff here...},
   target: {
      dest: '<%= grunt.tasks.current.args[0] %>.dmg'
   }
}

**Comment by htanjo** [comment]
Maybe you are missing **target** of appdmg task. The Grunt format is `'<task>:<target>:<arg>'`.
This code should work. I hope it helps.

``` js
grunt.initConfig({
  appdmg: {
    main: {  // <-- Define target "main"
      options: {...stuff here...},
      dest: '<%= grunt.task.current.args[0] %>.dmg'
    }
  }
});
grunt.loadNpmTasks('grunt-appdmg');
grunt.registerTask('release', function() {

  // OK: "volume1" will pass to args[0].
  grunt.task.run('appdmg:main:volume1');

  // NG: "volume1" will be handled as undefined target.
  // grunt.task.run('appdmg:volume1');

});
```

**Comment by conceptualspace** [comment]
that was it.. thanks :)
